# Generated by Django 4.1.7 on 2023-05-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_patient_nurse_driver_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
        migrations.DeleteModel(
            name='driver',
        ),
        migrations.DeleteModel(
            name='nurse',
        ),
        migrations.DeleteModel(
            name='patient',
        ),
    ]
