# Generated by Django 4.1.7 on 2023-05-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcenter',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
