# Generated by Django 4.1.7 on 2023-05-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_medicalcenter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
